; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Zero Example"
#define MyAppVersion "0.0.0"
#define MyAppPublisher "Řízek Jan"
#define MyAppURL "https://github.com/red-steak/ZeroExample"
#define MyAppExeName "ZeroExample.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2D2CD0C7-A4E8-4384-8AFC-3CDBE1E75D6F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample
OutputBaseFilename=ZeroExample-SETUP
SetupIconFile=C:\Users\hp\Pictures\TESCO SW IMAGES\icon.ico
SolidCompression=yes
WizardStyle=modern dark windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Images\about.png"; DestDir: "{app}\Images"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Images\generate.png"; DestDir: "{app}\Images"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Images\generate-with-errors.png"; DestDir: "{app}\Images"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Images\load-data.png"; DestDir: "{app}\Images"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Images\open-file.png"; DestDir: "{app}\Images"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Images\save-file.png"; DestDir: "{app}\Images"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Data\cars - 0000.xml"; DestDir: "{app}\Data"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ControlzEx.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Fluent.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Bcl.TimeProvider.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.Configuration.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.Diagnostics.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.FileProviders.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.Hosting.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Microsoft.Xaml.Behaviors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Models.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.Disposables.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.Primitives.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.Primitives.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ReactiveUI.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Splat.Builder.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Splat.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Splat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Splat.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\Splat.Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ViewModels.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ZeroExample.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ZeroExample.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\ZeroExample.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\hp\Documents\EXAMPLE TESCO SW\ZeroExample\ZeroExample\bin\Debug\net10.0-windows\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

